# client/Dockerfile.dev
FROM node:18-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

# copy rest (volume will override during docker run)
COPY . .

ENV CHOKIDAR_USEPOLLING=true
EXPOSE 3000
CMD ["npm", "start"]
