# client/nginx.conf
server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # caching for static assets
  location ~* \.(?:css|js|jpg|jpeg|png|gif|svg|ico|woff2?|map)$ {
    expires 7d;
    add_header Cache-Control "public";
  }

  gzip on;
  gzip_types text/plain application/javascript text/css application/json application/xml;
}
